version: '3.8'

services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20
    platform: linux/arm64
    environment:
      PGHOST: postgres
      PGUSER: dev
      PGPASSWORD: dev
      PGDATABASE: dev
    volumes:
      - home_dev:/home/dev
      - vscode_extensions:/home/dev/.vscode-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock
      
    ports:
      - 5173:5173
      - 5432:5432
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgweb:
    image: sosedoff/pgweb:0.11.11
    environment:
      - DATABASE_URL=postgres://dev:dev@postgres/dev?sslmode=disable
    ports:
      - 8082:8081
    depends_on:
      - postgres
    restart: always

volumes:
  home_dev:
  postgres_data:
  vscode_extensions:
